//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveDescribe.Resources.UiStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveDescribe.Resources.UiStrings.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Command_Accept {
            get {
                return ResourceManager.GetString("Command_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add space.
        /// </summary>
        public static string Command_AddSpace {
            get {
                return ResourceManager.GetString("Command_AddSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Command_Apply {
            get {
                return ResourceManager.GetString("Command_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Command_Cancel {
            get {
                return ResourceManager.GetString("Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Recording.
        /// </summary>
        public static string Command_CancelRecording {
            get {
                return ResourceManager.GetString("Command_CancelRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Command_Clear {
            get {
                return ResourceManager.GetString("Command_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Command_Close {
            get {
                return ResourceManager.GetString("Command_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string Command_CreateProject {
            get {
                return ResourceManager.GetString("Command_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete description.
        /// </summary>
        public static string Command_DeleteDescription {
            get {
                return ResourceManager.GetString("Command_DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Space.
        /// </summary>
        public static string Command_DeleteSpace {
            get {
                return ResourceManager.GetString("Command_DeleteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to description.
        /// </summary>
        public static string Command_GoToDescription {
            get {
                return ResourceManager.GetString("Command_GoToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to space.
        /// </summary>
        public static string Command_GoToSpace {
            get {
                return ResourceManager.GetString("Command_GoToSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string Command_Mute {
            get {
                return ResourceManager.GetString("Command_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Command_Ok {
            get {
                return ResourceManager.GetString("Command_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Command_OpenBrowserDialog {
            get {
                return ResourceManager.GetString("Command_OpenBrowserDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Command_Pause {
            get {
                return ResourceManager.GetString("Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Command_Play {
            get {
                return ResourceManager.GetString("Command_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Command_Record {
            get {
                return ResourceManager.GetString("Command_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string Command_ResetToDefault {
            get {
                return ResourceManager.GetString("Command_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Command_Save {
            get {
                return ResourceManager.GetString("Command_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        public static string Command_SetBeginTime {
            get {
                return ResourceManager.GetString("Command_SetBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        public static string Command_SetEndTime {
            get {
                return ResourceManager.GetString("Command_SetEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Command_StopPlaying {
            get {
                return ResourceManager.GetString("Command_StopPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string Command_StopRecord {
            get {
                return ResourceManager.GetString("Command_StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Extended Description.
        /// </summary>
        public static string Command_ToggleRecordExtended {
            get {
                return ResourceManager.GetString("Command_ToggleRecordExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnMute.
        /// </summary>
        public static string Command_UnMute {
            get {
                return ResourceManager.GetString("Command_UnMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not fine ffmeg.exe at location {0}.
        /// </summary>
        public static string Error_Format_FfmpegNotFound {
            get {
                return ResourceManager.GetString("Error_Format_FfmpegNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Description Text to SRT File.
        /// </summary>
        public static string Export_DescriptionSrtTitle {
            get {
                return ResourceManager.GetString("Export_DescriptionSrtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Space Text to SRT File.
        /// </summary>
        public static string Export_SpaceSrtTitle {
            get {
                return ResourceManager.GetString("Export_SpaceSrtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioSource.
        /// </summary>
        public static string Header_AudioSource {
            get {
                return ResourceManager.GetString("Header_AudioSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels.
        /// </summary>
        public static string Header_Channels {
            get {
                return ResourceManager.GetString("Header_Channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colours.
        /// </summary>
        public static string Header_ColourSettings {
            get {
                return ResourceManager.GetString("Header_ColourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Spaces.
        /// </summary>
        public static string Header_CompletedSpaces {
            get {
                return ResourceManager.GetString("Header_CompletedSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Text.
        /// </summary>
        public static string Header_DescriptionText {
            get {
                return ResourceManager.GetString("Header_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Header_Duration {
            get {
                return ResourceManager.GetString("Header_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End In Video.
        /// </summary>
        public static string Header_EndTime {
            get {
                return ResourceManager.GetString("Header_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Descriptions.
        /// </summary>
        public static string Header_ExtendedDescriptions {
            get {
                return ResourceManager.GetString("Header_ExtendedDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Header_NumberColumn {
            get {
                return ResourceManager.GetString("Header_NumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string Header_RegularDescriptions {
            get {
                return ResourceManager.GetString("Header_RegularDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Space/Description.
        /// </summary>
        public static string Header_SelectedItem {
            get {
                return ResourceManager.GetString("Header_SelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Header_SpaceCompleted {
            get {
                return ResourceManager.GetString("Header_SpaceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        public static string Header_Spaces {
            get {
                return ResourceManager.GetString("Header_Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Text.
        /// </summary>
        public static string Header_SpaceText {
            get {
                return ResourceManager.GetString("Header_SpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start In Video.
        /// </summary>
        public static string Header_StartTime {
            get {
                return ResourceManager.GetString("Header_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string Label_Begin {
            get {
                return ResourceManager.GetString("Label_Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Label_End {
            get {
                return ResourceManager.GetString("Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Left: {0}.
        /// </summary>
        public static string Label_Format_TimeLeft {
            get {
                return ResourceManager.GetString("Label_Format_TimeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a copy of video?.
        /// </summary>
        public static string Label_MakeCopy {
            get {
                return ResourceManager.GetString("Label_MakeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Location.
        /// </summary>
        public static string Label_ProjectLocation {
            get {
                return ResourceManager.GetString("Label_ProjectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string Label_ProjectName {
            get {
                return ResourceManager.GetString("Label_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPM Record Time.
        /// </summary>
        public static string Label_TimeToRecord {
            get {
                return ResourceManager.GetString("Label_TimeToRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use WPM Record Time.
        /// </summary>
        public static string Label_UseWpm {
            get {
                return ResourceManager.GetString("Label_UseWpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Label_Video {
            get {
                return ResourceManager.GetString("Label_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words Per Minute.
        /// </summary>
        public static string Label_WordsPerMinute {
            get {
                return ResourceManager.GetString("Label_WordsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh project cache.
        /// </summary>
        public static string MenuItem_ClearCache {
            get {
                return ResourceManager.GetString("MenuItem_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        public static string MenuItem_CloseProject {
            get {
                return ResourceManager.GetString("MenuItem_CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find spaces in video.
        /// </summary>
        public static string MenuItem_FindSpaces {
            get {
                return ResourceManager.GetString("MenuItem_FindSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string MenuItem_NewProject {
            get {
                return ResourceManager.GetString("MenuItem_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        public static string MenuItem_OpenProject {
            get {
                return ResourceManager.GetString("MenuItem_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string MenuItem_Preferences {
            get {
                return ResourceManager.GetString("MenuItem_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MenuItem_Project {
            get {
                return ResourceManager.GetString("MenuItem_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string MenuItem_SaveProject {
            get {
                return ResourceManager.GetString("MenuItem_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View LiveDescribe help.
        /// </summary>
        public static string MenuItem_ShowHelpWindow {
            get {
                return ResourceManager.GetString("MenuItem_ShowHelpWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio file for description could not be found at {0}.
        /// </summary>
        public static string MessageBox_Format_AudioFileNotFound {
            get {
                return ResourceManager.GetString("MessageBox_Format_AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} already exists. Do you wish to overwrite its contents?.
        /// </summary>
        public static string MessageBox_Format_OverwriteProjectWarning {
            get {
                return ResourceManager.GetString("MessageBox_Format_OverwriteProjectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LiveDescribe project &quot;{0}&quot; has been modified. Do you want to save changes before closing?.
        /// </summary>
        public static string MessageBox_Format_SaveProjectWarning {
            get {
                return ResourceManager.GetString("MessageBox_Format_SaveProjectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Microphone Connected.
        /// </summary>
        public static string MessageBox_NoMicrophoneFoundError {
            get {
                return ResourceManager.GetString("MessageBox_NoMicrophoneFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected project is missing file locations..
        /// </summary>
        public static string MessageBox_OpenProjectFileMissingError {
            get {
                return ResourceManager.GetString("MessageBox_OpenProjectFileMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while attempting to create the project..
        /// </summary>
        public static string MessageBox_ProjectCreationError {
            get {
                return ResourceManager.GetString("MessageBox_ProjectCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all colours to default?.
        /// </summary>
        public static string MessageBox_ResetColourSchemeWarning {
            get {
                return ResourceManager.GetString("MessageBox_ResetColourSchemeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBox_Title_ConfirmationWarning {
            get {
                return ResourceManager.GetString("MessageBox_Title_ConfirmationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Title_Error {
            get {
                return ResourceManager.GetString("MessageBox_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveDescribe Files (*{0})|*{0}|All Files(*.*)|*.*.
        /// </summary>
        public static string OpenFileDialog_Format_OpenProject {
            get {
                return ResourceManager.GetString("OpenFileDialog_Format_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2014.
        /// </summary>
        public static string Program_Copyright {
            get {
                return ResourceManager.GetString("Program_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiveDescribe.
        /// </summary>
        public static string Program_Name {
            get {
                return ResourceManager.GetString("Program_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusive Media and Design Centre.
        /// </summary>
        public static string Program_OrganizationName {
            get {
                return ResourceManager.GetString("Program_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ryerson University.
        /// </summary>
        public static string Program_OrganizationName2 {
            get {
                return ResourceManager.GetString("Program_OrganizationName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.1.
        /// </summary>
        public static string Program_VersionNumber {
            get {
                return ResourceManager.GetString("Program_VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.0.1.
        /// </summary>
        public static string Program_VersionString {
            get {
                return ResourceManager.GetString("Program_VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubRip Files (*.srt)|*.srt.
        /// </summary>
        public static string SaveFileDialog_ExportToSrt {
            get {
                return ResourceManager.GetString("SaveFileDialog_ExportToSrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark beginning of selected space.
        /// </summary>
        public static string ToolTip_MarkBeginning {
            get {
                return ResourceManager.GetString("ToolTip_MarkBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark end of selected space.
        /// </summary>
        public static string ToolTip_MarkEnd {
            get {
                return ResourceManager.GetString("ToolTip_MarkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours : Minutes : Seconds . Milliseconds.
        /// </summary>
        public static string ToolTip_MarkSpace {
            get {
                return ResourceManager.GetString("ToolTip_MarkSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Window_AboutTitle {
            get {
                return ResourceManager.GetString("Window_AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}* {1}.
        /// </summary>
        public static string Window_Format_MainWindowProjectModified {
            get {
                return ResourceManager.GetString("Window_Format_MainWindowProjectModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string Window_Format_MainWindowProjectSaved {
            get {
                return ResourceManager.GetString("Window_Format_MainWindowProjectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new LiveDescribe Project.
        /// </summary>
        public static string Window_NewProjectTitle {
            get {
                return ResourceManager.GetString("Window_NewProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Window_PreferencesTitle {
            get {
                return ResourceManager.GetString("Window_PreferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record a Description.
        /// </summary>
        public static string Window_SpaceRecordingTitle {
            get {
                return ResourceManager.GetString("Window_SpaceRecordingTitle", resourceCulture);
            }
        }
    }
}
