//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveDescribe.Resources.UiStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveDescribe.Resources.UiStrings.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Command_Clear {
            get {
                return ResourceManager.GetString("Command_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete description.
        /// </summary>
        public static string Command_DeleteDescription {
            get {
                return ResourceManager.GetString("Command_DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Space.
        /// </summary>
        public static string Command_DeleteSpace {
            get {
                return ResourceManager.GetString("Command_DeleteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to description.
        /// </summary>
        public static string Command_GoToDescription {
            get {
                return ResourceManager.GetString("Command_GoToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to space.
        /// </summary>
        public static string Command_GoToSpace {
            get {
                return ResourceManager.GetString("Command_GoToSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Command_Record {
            get {
                return ResourceManager.GetString("Command_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string Command_StopRecord {
            get {
                return ResourceManager.GetString("Command_StopRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Text.
        /// </summary>
        public static string Header_DescriptionText {
            get {
                return ResourceManager.GetString("Header_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Header_Duration {
            get {
                return ResourceManager.GetString("Header_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End In Video.
        /// </summary>
        public static string Header_EndTime {
            get {
                return ResourceManager.GetString("Header_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Descriptions.
        /// </summary>
        public static string Header_ExtendedDescriptions {
            get {
                return ResourceManager.GetString("Header_ExtendedDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string Header_NumberColumn {
            get {
                return ResourceManager.GetString("Header_NumberColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string Header_RegularDescriptions {
            get {
                return ResourceManager.GetString("Header_RegularDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Header_SpaceCompleted {
            get {
                return ResourceManager.GetString("Header_SpaceCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spaces.
        /// </summary>
        public static string Header_Spaces {
            get {
                return ResourceManager.GetString("Header_Spaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Text.
        /// </summary>
        public static string Header_SpaceText {
            get {
                return ResourceManager.GetString("Header_SpaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start In Video.
        /// </summary>
        public static string Header_StartTime {
            get {
                return ResourceManager.GetString("Header_StartTime", resourceCulture);
            }
        }
    }
}
